CREATE TABLE WASTE_MANAGER(
    ID INT NOT NULL  AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    NIF VARCHAR(100) NOT NULL,
    IS_ENABLE BIT DEFAULT (1),
    VERSION INT DEFAULT (0),
    CREATED_DATE DATETIME DEFAULT (NOW()),
    LAST_MODIFIED_DATE DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE WASTE_MANAGER_ADDRESS(
    ID INT NOT NULL  AUTO_INCREMENT,
    DIRECCION VARCHAR(100) NOT NULL,
    IS_ENABLE BIT DEFAULT (1),
    VERSION INT DEFAULT (0),
    CREATED_DATE DATETIME DEFAULT (NOW()),
    LAST_MODIFIED_DATE DATETIME,
    WASTE_MANAGER_ID INT NOT NULL UNIQUE,
    PRIMARY KEY (ID),
    CONSTRAINT ADDRESS_WASTE_MANAGER_FK FOREIGN KEY (WASTE_MANAGER_ID) REFERENCES WASTE_MANAGER
);

CREATE TABLE WASTE_CENTER_AUTHORIZATION(
    ID INT NOT NULL  AUTO_INCREMENT,
    AUTHORIZATION_NUMBER VARCHAR(100) NOT NULL,
    WASTE_MANAGER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CENTER_AUTHORIZATION_WASTE_MANAGER_FK FOREIGN KEY (WASTE_MANAGER_ID) REFERENCES WASTE_MANAGER
);